### ISSUE TITLE
Settle on an error handling strategy for unsupported messages

### ISSUE THREAD

**Issue by thfis-dfds** [dfds/dafda#1]
When receiving bad formed, or "unknown" message, we need to figure out how to handle that, and not just fail spectacularly.

The configuration could supply a means for supplying an error handling strategy.

**Comment by martinosk** [comment]
Yeah, this would be great. I would prefer a "log and ignore" strategy as default, at least for unknown messages, because I don't think the consumer should be required to know all of the message types it can expect within a topic. 
For bad formed messages, I might still prefer to throw errors or similar.
