### ISSUE TITLE
Enabling auto commit in consumer

### ISSUE THREAD

**Issue by jandr-dfds** [dfds/dafda#2]

**Comment by martinosk** [comment]
I have a branch ready for this. Please give me access to push branches and create pull requests.

**Comment by jandr-dfds** [comment]
Fork and PR ?

**Comment by thfis-dfds** [comment]
Should the default behavior for auto commit be _enabled_ or _disabled_?

**Comment by jandr-dfds** [comment]
It's set to true by default when looking at the librdkafka doc:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Maybe we should also set it to true (even if the configuration value is omitted) and only set it to false when it has explicitly been set as a configuration value (e.g. `enable.auto.commit=false`).

Thoughts?

**Comment by thfis-dfds** [comment]
Apparently it may differ from client library to client library, but (as @jandr-dfds mentioned) librdkafka and therefore also the .NET Kafka library uses `true` as default. It's the same for consumer configuration in Confluent's documentation.

It is also our default "[strategy](https://github.com/dfds/dafda/blob/64ac5678010734523da2191a248b54efbcb02faa/src/Dafda/Configuration/ConsumerConfigurationBuilder.cs#L190)"

Going forward I'm a little uncertain what the best bet should be for these types of configuration values.
On the one hand, not specifying `enable.auto.commit=false` (either in environment or directly through `WithConfiguration(...)` means that value is not presented to the underlying Kafka consumer, since it's not part of the provided configuration, which in turn means it will rely on defaults (will they change?)
On the other hand, this may be too implicit, but maybe no more than librdkafka though.

For now I am partial to leaving it as "_working as intended_"...

**Comment by jandr-dfds** [comment]
Is implemented
