### ISSUE TITLE
Ignore messages that do not follow the expected envelope standard

### ISSUE THREAD

**Issue by cristian-dfds** [dfds/dafda#51]
When trying to consume a message that does not have the "data" field, we get an exception:
Unhandled error occurred while consuming messaging","@x":"System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
Instead of throwing an exception the library should ignore these messages.

**Comment by chamook** [comment]
FWIW this is probably caused by the [`JsonIncomingMessageFactory`](https://github.com/dfds/dafda/blob/master/src/Dafda/Consuming/JsonIncomingMessageFactory.cs#L20) and can be worked around for now by providing a custom implementation of `IIncomingMessageFactory` for a consumer. 

Might be worth considering including multiple out-of-the-box options instead of just modifying the existing one when working on this :)

**Comment by jakob-nielsen-dfds** [comment]
Isn't that somewhat intentional as this is the envelope standard we try to follow in DFDS - https://wiki.dfds.cloud/playbooks/standards/dfds_std_publicevents001 ?

It might be a hindrance if others want to use the library in a different way. So might be okay to support it.

**Comment by dingobar** [comment]
It creates an issue when consuming events from sources such as kafka connect, which do not have the envelope (usually). Perhaps some sort of flag that can be set when creating the consumer?

**Comment by jakob-nielsen-dfds** [comment]
> It creates an issue when consuming events from sources such as kafka connect, which do not have the envelope (usually). Perhaps some sort of flag that can be set when creating the consumer?

Makes sense. Would be a shame to limit the library for other use-cases.

**Comment by cristian-dfds** [comment]
It is currently enforcing that the message has a "data" field, so whoever is using the library is already following at least this convention. We don't need to enforce the whole standard. I'll try to make a different MessageFactory that ignores messages that don't contain the data field on root level.

**Comment by chamook** [comment]
It would be a breaking change if we _stopped_ throwing for it by default - so the gentlest change for users of the package would be to add alternatives to the default implementation, and make it easy to switch to them.

**Comment by cristian-dfds** [comment]
I don't really see that as a breaking change. the library crashes your application unless you handle a KeyNotFoundException when the data field is missing. Whoever is using this library needs to handle a weird exception or always make sure not to have invalid messages on the topics.

**Comment by chamook** [comment]
It's a breaking change because it would alter the observable behaviour of the system in such a way that may break things for a user of the library :)

An application might be setup to catch the `KeyNotFoundException` and provide metrics about invalid messages - this would be broken by updating to a newer version of the library that changed that behaviour.

Alternatively - a _creative_ user of the library might wish to send a malformed message to prevent an application from consuming events beyond a certain point in a queue without manual intervention - this would be broken by updating to a newer version of the library that changed the behaviour.

I'm not saying that we shouldn't change how it works, because all of these things seem at best unergonomic - but it is a significant change to behaviour that users might be relying on, so that should be considered.

There are, as I see it, several ways to proceed in light of that:

- **do nothing** - this obviously sucks because we don't really like the current behaviour, but it is the least risky
- **add an optional way of configuring things, while keeping the current behaviour default** - this would preserve the current behaviour for those who want it while making it easier to change for those who don't, but notably wouldn't force any changes and break anything quietly
- **require extra configuration to determine this behaviour** - if we can make it so that the application won't compile without specifying behaviour we avoid anything being deployed with potentially unexpected behaviour; if the best we can do is failing on startup then at least we will be failing fast

and as a last resort:

- **make a breaking change and reflect it in the version** - this would let us make the most significant changes to the default behaviour, but we don't really have a proper versioning policy for this library so it wouldn't necessarily be clear to end users

Remember that dafda is an open library that could potentially be used in a lot of different scenarios, we should respect that whenever we make changes to it :)

**Comment by martinosk** [comment]
@jakob-nielsen-dfds I agree that this is somewhat intentional. Dafda is intended to be opinionated and enforcing a specific envelope style and helping with pub/sub style implementations. I don't see a point in making Dafda an all purpose Kafka abstraction. We already have Confluent.Kafka for that. I think @dingobar is better of not using Dafda for consuming raw kafka connect messages.

That said, I think it makes sense to allow other ways of handling "transport level" poison messages than throwing exceptions. Perhaps ignoring them as @cristian-dfds suggests or ignore them and copy them to a poison topic.

**Comment by dingobar** [comment]
>  I think @dingobar is better of not using Dafda for consuming raw kafka connect messages.
I'm fine with this.
